@startuml InGameUILogic
state InGameUILogic {
  state BaseState
}

[*] --> BaseState

InGameUILogic : Dependencies:
InGameUILogic : - IAppRepo
InGameUILogic : - IGameRepo
InGameUILogic : - Mock
@enduml