@startuml CoinLogic
state CoinLogic {
  state Idle
}

[*] --> Idle

CoinLogic : Dependencies:
CoinLogic : - Data
CoinLogic : - EntityTable
CoinLogic : - ICoin
CoinLogic : - IGameRepo
CoinLogic : - Settings
@enduml