@startuml CoinLogic
state "CoinLogic State" as GameDemo_CoinLogic_State {
  state "Collecting" as GameDemo_CoinLogic_State_Collecting
  state "Idle" as GameDemo_CoinLogic_State_Idle
}

GameDemo_CoinLogic_State_Collecting --> GameDemo_CoinLogic_State_Collecting : PhysicsProcess
GameDemo_CoinLogic_State_Idle --> GameDemo_CoinLogic_State_Collecting : StartCollection

GameDemo_CoinLogic_State_Collecting : OnPhysicsProcess → Move, SelfDestruct

[*] --> GameDemo_CoinLogic_State_Idle
@enduml