@startuml PlayerLogicState
state "PlayerLogicState" as GameDemo_PlayerLogicState {
  state "Alive" as GameDemo_PlayerLogicState_Alive {
    state "Airborne" as GameDemo_PlayerLogicState_Airborne {
      state "Falling" as GameDemo_PlayerLogicState_Falling
      state "Jumping" as GameDemo_PlayerLogicState_Jumping
      state "Liftoff" as GameDemo_PlayerLogicState_Liftoff
    }
    state "Grounded" as GameDemo_PlayerLogicState_Grounded {
      state "Idle" as GameDemo_PlayerLogicState_Idle
      state "Moving" as GameDemo_PlayerLogicState_Moving
    }
  }
  state "Dead" as GameDemo_PlayerLogicState_Dead
  state "Disabled" as GameDemo_PlayerLogicState_Disabled
}

GameDemo_PlayerLogicState_Airborne --> GameDemo_PlayerLogicState_Falling : StartedFalling
GameDemo_PlayerLogicState_Airborne --> GameDemo_PlayerLogicState_Idle : HitFloor
GameDemo_PlayerLogicState_Airborne --> GameDemo_PlayerLogicState_Moving : HitFloor
GameDemo_PlayerLogicState_Alive --> GameDemo_PlayerLogicState_Alive : Moved
GameDemo_PlayerLogicState_Alive --> GameDemo_PlayerLogicState_Alive : PhysicsTick
GameDemo_PlayerLogicState_Alive --> GameDemo_PlayerLogicState_Alive : Pushed
GameDemo_PlayerLogicState_Alive --> GameDemo_PlayerLogicState_Dead : Killed
GameDemo_PlayerLogicState_Disabled --> GameDemo_PlayerLogicState_Idle : Enable
GameDemo_PlayerLogicState_Grounded --> GameDemo_PlayerLogicState_Falling : LeftFloor
GameDemo_PlayerLogicState_Grounded --> GameDemo_PlayerLogicState_Jumping : Jump
GameDemo_PlayerLogicState_Grounded --> GameDemo_PlayerLogicState_Liftoff : LeftFloor
GameDemo_PlayerLogicState_Idle --> GameDemo_PlayerLogicState_Moving : StartedMovingHorizontally
GameDemo_PlayerLogicState_Jumping --> GameDemo_PlayerLogicState_Jumping : Jump
GameDemo_PlayerLogicState_Moving --> GameDemo_PlayerLogicState_Idle : StoppedMovingHorizontally

GameDemo_PlayerLogicState_Alive : OnPhysicsTick → MovementComputed
GameDemo_PlayerLogicState_Alive : OnPushed → VelocityChanged
GameDemo_PlayerLogicState_Disabled : OnEnter → Idle
GameDemo_PlayerLogicState_Falling : OnEnter → Fall
GameDemo_PlayerLogicState_Grounded : OnJump → VelocityChanged
GameDemo_PlayerLogicState_Idle : OnEnter → Idle
GameDemo_PlayerLogicState_Jumping : OnEnter → Jump
GameDemo_PlayerLogicState_Jumping : OnJump → VelocityChanged
GameDemo_PlayerLogicState_Liftoff : OnEnter → Jump
GameDemo_PlayerLogicState_Moving : OnEnter → Move
@enduml