@startuml PlayerLogic
state "PlayerLogic State" as GameDemo_PlayerLogic_State {
  state "Alive" as GameDemo_PlayerLogic_State_Alive {
    state "Airborne" as GameDemo_PlayerLogic_State_Airborne {
      state "Falling" as GameDemo_PlayerLogic_State_Falling
      state "Jumping" as GameDemo_PlayerLogic_State_Jumping
      state "Liftoff" as GameDemo_PlayerLogic_State_Liftoff
    }
    state "Grounded" as GameDemo_PlayerLogic_State_Grounded {
      state "Idle" as GameDemo_PlayerLogic_State_Idle
      state "Moving" as GameDemo_PlayerLogic_State_Moving
    }
  }
  state "Dead" as GameDemo_PlayerLogic_State_Dead
  state "Disabled" as GameDemo_PlayerLogic_State_Disabled
}

GameDemo_PlayerLogic_State_Airborne --> GameDemo_PlayerLogic_State_Falling : StartedFalling
GameDemo_PlayerLogic_State_Airborne --> GameDemo_PlayerLogic_State_Idle : HitFloor
GameDemo_PlayerLogic_State_Airborne --> GameDemo_PlayerLogic_State_Moving : HitFloor
GameDemo_PlayerLogic_State_Alive --> GameDemo_PlayerLogic_State_Alive : Moved
GameDemo_PlayerLogic_State_Alive --> GameDemo_PlayerLogic_State_Alive : PhysicsTick
GameDemo_PlayerLogic_State_Alive --> GameDemo_PlayerLogic_State_Alive : Pushed
GameDemo_PlayerLogic_State_Alive --> GameDemo_PlayerLogic_State_Dead : Killed
GameDemo_PlayerLogic_State_Disabled --> GameDemo_PlayerLogic_State_Idle : Enable
GameDemo_PlayerLogic_State_Grounded --> GameDemo_PlayerLogic_State_Falling : LeftFloor
GameDemo_PlayerLogic_State_Grounded --> GameDemo_PlayerLogic_State_Jumping : Jump
GameDemo_PlayerLogic_State_Grounded --> GameDemo_PlayerLogic_State_Liftoff : LeftFloor
GameDemo_PlayerLogic_State_Idle --> GameDemo_PlayerLogic_State_Moving : StartedMovingHorizontally
GameDemo_PlayerLogic_State_Jumping --> GameDemo_PlayerLogic_State_Jumping : Jump
GameDemo_PlayerLogic_State_Moving --> GameDemo_PlayerLogic_State_Idle : StoppedMovingHorizontally

GameDemo_PlayerLogic_State_Alive : OnPhysicsTick → MovementComputed
GameDemo_PlayerLogic_State_Alive : OnPushed → VelocityChanged
GameDemo_PlayerLogic_State_Disabled : OnEnter → Idle
GameDemo_PlayerLogic_State_Falling : OnEnter → Fall
GameDemo_PlayerLogic_State_Grounded : OnJump → VelocityChanged
GameDemo_PlayerLogic_State_Idle : OnEnter → Idle
GameDemo_PlayerLogic_State_Jumping : OnEnter → Jump
GameDemo_PlayerLogic_State_Jumping : OnJump → VelocityChanged
GameDemo_PlayerLogic_State_Liftoff : OnEnter → Jump
GameDemo_PlayerLogic_State_Moving : OnEnter → Move

[*] --> GameDemo_PlayerLogic_State_Disabled
@enduml