@startuml BaseState
state "BaseState" as GameDemo_PlayerLogic_BaseState {
  state "Alive" as GameDemo_PlayerLogic_BaseState_Alive {
    state "Airborne" as GameDemo_PlayerLogic_BaseState_Airborne {
      state "Falling" as GameDemo_PlayerLogic_BaseState_Falling
      state "Jumping" as GameDemo_PlayerLogic_BaseState_Jumping
      state "Liftoff" as GameDemo_PlayerLogic_BaseState_Liftoff
      state "TestPlayerState" as GameDemo_Tests_PlayerLogicStateAliveAirborneTest_TestPlayerState
    }
    state "Grounded" as GameDemo_PlayerLogic_BaseState_Grounded {
      state "Idle" as GameDemo_PlayerLogic_BaseState_Idle
      state "Moving" as GameDemo_PlayerLogic_BaseState_Moving
      state "TestPlayerState" as GameDemo_Tests_PlayerLogicStateAliveGroundedTest_TestPlayerState
    }
    state "TestPlayerState" as GameDemo_Tests_PlayerLogicStateAliveTest_TestPlayerState
  }
  state "Dead" as GameDemo_PlayerLogic_BaseState_Dead
  state "Disabled" as GameDemo_PlayerLogic_BaseState_Disabled
}

GameDemo_PlayerLogic_BaseState_Airborne --> GameDemo_PlayerLogic_BaseState_Falling : StartedFalling
GameDemo_PlayerLogic_BaseState_Airborne --> GameDemo_PlayerLogic_BaseState_Idle : HitFloor
GameDemo_PlayerLogic_BaseState_Airborne --> GameDemo_PlayerLogic_BaseState_Moving : HitFloor
GameDemo_PlayerLogic_BaseState_Alive --> GameDemo_PlayerLogic_BaseState_Alive : Moved
GameDemo_PlayerLogic_BaseState_Alive --> GameDemo_PlayerLogic_BaseState_Alive : PhysicsTick
GameDemo_PlayerLogic_BaseState_Alive --> GameDemo_PlayerLogic_BaseState_Alive : Pushed
GameDemo_PlayerLogic_BaseState_Alive --> GameDemo_PlayerLogic_BaseState_Dead : Killed
GameDemo_PlayerLogic_BaseState_Disabled --> GameDemo_PlayerLogic_BaseState_Idle : Enable
GameDemo_PlayerLogic_BaseState_Grounded --> GameDemo_PlayerLogic_BaseState_Falling : LeftFloor
GameDemo_PlayerLogic_BaseState_Grounded --> GameDemo_PlayerLogic_BaseState_Jumping : Jump
GameDemo_PlayerLogic_BaseState_Grounded --> GameDemo_PlayerLogic_BaseState_Liftoff : LeftFloor
GameDemo_PlayerLogic_BaseState_Idle --> GameDemo_PlayerLogic_BaseState_Moving : StartedMovingHorizontally
GameDemo_PlayerLogic_BaseState_Jumping --> GameDemo_PlayerLogic_BaseState_Jumping : Jump
GameDemo_PlayerLogic_BaseState_Moving --> GameDemo_PlayerLogic_BaseState_Idle : StoppedMovingHorizontally

GameDemo_PlayerLogic_BaseState_Alive : OnPhysicsTick → MovementComputed
GameDemo_PlayerLogic_BaseState_Alive : OnPushed → VelocityChanged
GameDemo_PlayerLogic_BaseState_Disabled : OnEnter → Idle
GameDemo_PlayerLogic_BaseState_Falling : OnEnter → Fall
GameDemo_PlayerLogic_BaseState_Grounded : OnJump → VelocityChanged
GameDemo_PlayerLogic_BaseState_Idle : OnEnter → Idle
GameDemo_PlayerLogic_BaseState_Jumping : OnEnter → Jump
GameDemo_PlayerLogic_BaseState_Jumping : OnJump → VelocityChanged
GameDemo_PlayerLogic_BaseState_Liftoff : OnEnter → Jump
GameDemo_PlayerLogic_BaseState_Moving : OnEnter → Move
@enduml