@startuml

package App-Scene [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.tscn]] {
    class App  {
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs ScriptFile]]
        [Nodes]
        Menu - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs Script]]
        Splash - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/splash/Splash.cs Script]]
        [Properties]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:51 AnimationPlayer]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:42 AppBinding]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:40 AppLogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/state/states/SplashScreen.cs Script]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:39 AppRepo]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:50 BlankScreen]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:26 Game]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs Script]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:49 GamePreview]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:27 Instantiator]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/utils/Instantiator.cs Script]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:48 Menu]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs Script]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:52 Splash]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/splash/Splash.cs Script]]
        --
        [Methods]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:16 _Notification()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:151 FadeInFromBlack()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:157 FadeToBlack()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:163 HideMenus()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:56 Initialize()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:135 OnAnimationFinished()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:169 OnExitTree()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:133 OnLoadGame()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:131 OnNewGame()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:74 OnReady()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/app/App.cs:181 OnSaveFileLoaded()]]
    }
    class Menu  {
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs ScriptFile]]
        [Properties]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs:22 LoadGameButton]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs:20 NewGameButton]]
        --
        [Methods]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs:17 _Notification()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs:39 OnExitTree()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs:46 OnLoadGamePressed()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs:45 OnNewGamePressed()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/Menu.cs:33 OnReady()]]
    }
    class Splash  {
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/splash/Splash.cs ScriptFile]]
        [Properties]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/splash/Splash.cs:16 AnimationPlayer]]
        --
        [Methods]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/splash/Splash.cs:34 _Input()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/splash/Splash.cs:13 _Notification()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/splash/Splash.cs:31 OnAnimationFinished()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/splash/Splash.cs:28 OnExitTree()]]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/menu/splash/Splash.cs:25 OnReady()]]
    }
    package Game-Scene [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.tscn]] {
        class Game  {
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs ScriptFile]]
            [Nodes]
            PlayerCamera - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs Script]]
            Player - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs Script]]
            Map - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs Script]]
            InGameUi - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs Script]]
            InGameAudio - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs Script]]
            DeathMenu - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs Script]]
            WinMenu - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs Script]]
            PauseMenu - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs Script]]
            [Properties]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:62 DeathMenu]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs Script]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:38 EntityTable]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:36 Environment]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:35 FileSystem]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:50 GameBinding]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:41 GameChunk]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:48 GameLogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/state/states/Won.cs Script]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:47 GameRepo]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:61 InGameUi]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs Script]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:33 JsonOptions]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:60 Map]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs Script]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:64 PauseMenu]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs Script]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:58 Player]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs Script]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:56 PlayerCamera]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs Script]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:40 SaveFile]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:37 SaveFilePath]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:63 WinMenu]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs Script]]
            --
            [Interface Methods]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:284 LoadExistingGame()]]
            [Methods]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:240 _Input()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:28 _Notification()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:290 FinishedLoadingSaveFile()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:266 OnDeathMenuTransitioned()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:269 OnExitTree()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:248 OnMainMenu()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:263 OnPauseMenuSaveRequested()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:260 OnPauseMenuTransitioned()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:152 OnResolved()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:251 OnResume()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:254 OnStart()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:257 OnWinMenuTransitioned()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:293 SetPauseMode()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/game/Game.cs:80 Setup()]]
        }
        package PlayerCamera-Scene [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.tscn]] {
            class PlayerCamera  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs ScriptFile]]
                [Interface Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:114 CameraBasis]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:110 CameraLocalPosition]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:75 CameraLogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/State/states/PlayerCameraLogic.State.InputEnabled.cs Script]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:111 GimbalRotationHorizontal]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:112 GimbalRotationVertical]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:83 Offset]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:117 OffsetPosition]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:109 SpringArmTargetPosition]]
                [Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:77 CameraBinding]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:100 CameraNode]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:94 GimbalHorizontalNode]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:97 GimbalVerticalNode]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:92 OffsetNode]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:69 PlayerCameraChunk]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:85 Settings]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCameraSettings.cs Script]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:102 SpringArmTarget]]
                --
                [Interface Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:218 UsePlayerCamera()]]
                [Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:210 _Input()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:63 _Notification()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:220 OnExitTree()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:185 OnPhysicsProcess()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:160 OnResolved()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCamera.cs:121 Setup()]]
            }
            class PlayerCameraSettings  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCameraSettings.cs ScriptFile]]
                [Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCameraSettings.cs:11 JoypadSensitivity]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCameraSettings.cs:8 MouseSensitivity]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCameraSettings.cs:17 VerticalMax]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player_camera/PlayerCameraSettings.cs:23 VerticalMin]]
            }
            PlayerCamera::PlayerCameraSettings ---> PlayerCameraSettings
        }
        package Player-Scene [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.tscn]] {
            class Player  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs ScriptFile]]
                [Provisions]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:60 IPlayerLogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/state/states/PlayerLogic.State.Disabled.cs Script]]
                --
                [Interface Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:111 PlayerLogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/state/states/PlayerLogic.State.Disabled.cs Script]]
                [Nodes]
                PlayerModel - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/PlayerModel.tscn Script]]
                [Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:93 Acceleration]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:266 CenterOfMass]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:85 Gravity]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:104 JumpForce]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:97 JumpImpulseForce]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:89 MoveSpeed]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:114 PlayerBinding]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:55 PlayerChunk]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:77 RotationSpeed]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:112 Settings]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:81 StoppingSpeed]]
                --
                [Interface Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:214 GetGlobalInputVector()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:230 GetNextRotationBasis()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:251 IsMovingHorizontally()]]
                [Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:47 _Notification()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:272 Kill()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:157 OnExitTree()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:190 OnPhysicsProcess()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:155 OnReady()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:164 OnResolved()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:259 Push()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:118 Setup()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/Player.cs:209 ShouldJump()]]
            }
            class PlayerModel << (S,black) >> {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/PlayerModel.tscn SceneFile]]
                [Nodes]
                chicken - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/player/visuals/chicken/chicken.tscn Script]]
            }
            Player::PlayerModel ---> PlayerModel
        }
        package Map-Scene [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.tscn]] {
            class Map  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs ScriptFile]]
                [Nodes]
                terrain - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/terrain/terrain.tscn Script]]
                DeathPlane - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_plane/DeathPlane.cs Script]]
                Tree1Geo - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo34 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo2 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo13 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo3 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo6 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo9 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo12 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo26 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo27 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo28 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo30 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo31 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo32 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo33 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo35 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo37 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo38 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo41 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo42 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo43 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo14 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo15 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo17 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo18 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo21 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo24 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/trees/tree.tscn Script]]
                TreeTrunkSmall2 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                TreeTrunkSmall - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                LargeTreeTrunk - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/large_tree_trunk/LargeTreeTrunk.tscn Script]]
                Jumpshroom2 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom4 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom3 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom5 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom9 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom6 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom8 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom7 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Bush1 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush2 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush3 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush4 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush7 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush5 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush6 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/bushes/bush.tscn Script]]
                Coin - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin26 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin27 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin28 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin29 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin30 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin43 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin44 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin31 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin2 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin32 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin42 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin33 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin19 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin24 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin25 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin20 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin22 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin3 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin4 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin9 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin12 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin15 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin16 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin13 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin14 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin38 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin39 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin41 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin37 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin5 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin6 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin7 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin8 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin10 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin40 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin17 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin11 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin34 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                Coin36 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                TreeTrunkSmall - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                Jumpshroom - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Fence - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence2 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence3 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence4 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence8 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence12 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence13 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence9 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence10 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence11 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence14 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence15 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence16 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence17 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence5 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence6 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence7 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/fence/Fence.tscn Script]]
                Cloud - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/cloud/Cloud.tscn Script]]
                Cloud2 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/cloud/Cloud.tscn Script]]
                Cloud3 - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/cloud/Cloud.tscn Script]]
                [Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs:37 Coins]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs:30 MapChunk]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs:44 MapLogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/state/MapLogic.State.cs Script]]
                --
                [Interface Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs:48 GetCoinCount()]]
                [Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs:21 _Notification()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs:52 OnResolved()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/Map.cs:50 Setup()]]
            }
            class terrain << (S,black) >> {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/terrain/terrain.tscn SceneFile]]
                [Nodes]
                Waterfall - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/map/waterfall/waterfall.tscn Script]]
            }
            class DeathPlane  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_plane/DeathPlane.cs ScriptFile]]
                [Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_plane/DeathPlane.cs:10 _Notification()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_plane/DeathPlane.cs:16 OnBodyEntered()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_plane/DeathPlane.cs:14 OnExitTree()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_plane/DeathPlane.cs:12 OnReady()]]
            }
            class Jumpshroom  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs ScriptFile]]
                [Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:43 AnimationPlayer]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:44 Area3D]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:45 CooldownTimer]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:36 ImpulseStrength]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:33 JumpshroomBinding]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:31 JumpshroomLogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/state/states/JumpshroomLogic.State.Loading.cs Script]]
                --
                [Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:20 _Notification()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:105 OnAnimationFinished()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:87 OnAreaBodyEntered()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:85 OnCooldownTimeout()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:108 OnExitTree()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:61 OnResolved()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:97 OnShroomLoaded()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/jumpshroom/Jumpshroom.cs:55 Setup()]]
            }
            class Coin  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs ScriptFile]]
                [Interface Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:37 CoinLogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/state/states/CoinLogic.State.Idle.cs Script]]
                [Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:22 AnimationPlayer]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:40 CoinBinding]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:23 CoinModel]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:29 CollectionTimeInSeconds]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:46 CollectorDetector]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:38 Settings]]
                --
                [Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:18 _Notification()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:111 OnCollectorDetectorBodyEntered()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:121 OnExitTree()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:108 OnPhysicsProcess()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:63 OnReady()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:78 OnResolved()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs:51 Setup()]]
            }
            Map::terrain ---> terrain
            Map::DeathPlane ---> DeathPlane
            Map::Jumpshroom2 ---> Jumpshroom
            Map::Coin ---> Coin
        }
        package InGameUI-Scene [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.tscn]] {
            class InGameUI  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs ScriptFile]]
                [Nodes]
                CoinScene - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/coin_scene/CoinScene.tscn Script]]
                [Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs:28 CoinsLabel]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs:36 InGameUIBinding]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs:34 InGameUILogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/state/InGameUILogic.State.cs Script]]
                --
                [Interface Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs:60 SetCoinsLabel()]]
                [Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs:17 _Notification()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs:63 OnExitTree()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs:42 OnResolved()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/InGameUI.cs:40 Setup()]]
            }
            package CoinScene-Scene [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/coin_scene/CoinScene.tscn]] {
                class CoinScene << (S,black) >> {
                    [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_ui/coin_scene/CoinScene.tscn SceneFile]]
                    [Nodes]
                    UICoin - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/coin/Coin.cs Script]]
                }

                CoinScene::UICoin ---> Coin
            }
            InGameUI::CoinScene ---> CoinScene
        }
        package InGameAudio-Scene [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.tscn]] {
            class InGameAudio  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs ScriptFile]]
                [Nodes]
                GameMusic - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                MainMenuMusic - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:17 Bounce]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:16 CoinCollected]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:21 GameMusic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:37 InGameAudioBinding]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:35 InGameAudioLogic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/state/InGameAudioLogic.State.cs Script]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:20 MainMenuMusic]] - [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:18 PlayerDied]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:19 PlayerJumped]]
                --
                [Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:12 _Notification()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:72 OnExitTree()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:43 OnResolved()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:41 Setup()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:85 StartGameMusic()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/InGameAudio.cs:78 StartMainMenuMusic()]]
            }
            class DimmableAudioStreamPlayer  {
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs ScriptFile]]
                [Properties]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:23 FadeTween]]
                --
                [Interface Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:33 FadeIn()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:39 FadeOut()]]
                [Methods]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:27 _Ready()]]
                [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:45 SetupFade()]]
            }
            InGameAudio::GameMusic ---> DimmableAudioStreamPlayer
        }
        class DeathMenu  {
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:38 AnimationPlayer]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:39 FadeAnimationPlayer]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:37 MainMenuButton]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:36 TryAgainButton]]
            --
            [Interface Methods]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:57 Animate()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:60 FadeIn()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:62 FadeOut()]]
            [Methods]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:23 _Notification()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:68 OnAnimationFinished()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:50 OnExitTree()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:66 OnMainMenuPressed()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:43 OnReady()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/death_menu/DeathMenu.cs:64 OnTryAgainPressed()]]
        }
        class WinMenu  {
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs:26 AnimationPlayer]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs:25 MainMenuButton]]
            --
            [Interface Methods]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs:46 FadeIn()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs:51 FadeOut()]]
            [Methods]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs:21 _Notification()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs:48 OnAnimationFinished()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs:42 OnExitTree()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs:44 OnMainMenuPressed()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/win_menu/WinMenu.cs:40 OnReady()]]
        }
        class PauseMenu  {
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:32 AnimationPlayer]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:31 MainMenuButton]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:29 ResumeButton]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:30 SaveButton]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:34 SaveOverlay]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:33 SaveOverlayAnimationPlayer]]
            --
            [Interface Methods]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:74 FadeIn()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:79 FadeOut()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:82 OnSaveCompleted()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:81 OnSaveStarted()]]
            [Methods]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:25 _Notification()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:85 Animate()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:76 OnAnimationFinished()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:62 OnExitTree()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:70 OnMainMenuPressed()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:54 OnReady()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:71 OnResumePressed()]]
            [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/pause_menu/PauseMenu.cs:72 OnSavePressed()]]
        }
        Game::PlayerCamera ---> PlayerCamera
        Game::Player ---> Player
        Game::Map ---> Map
        Game::InGameUi ---> InGameUI
        Game::InGameAudio ---> InGameAudio
        Game::DeathMenu ---> DeathMenu
        Game::WinMenu ---> WinMenu
        Game::PauseMenu ---> PauseMenu
    }
    class Instantiator  {
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/utils/Instantiator.cs ScriptFile]]
        [Interface Properties]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/utils/Instantiator.cs:27 SceneTree]]
        --
        [Interface Methods]
        [[vscode://file//Users/bastani/RiderProjects/GameDemo/src/utils/Instantiator.cs:34 LoadAndInstantiate()]]
    }
    App::Menu ---> Menu
    App::Splash ---> Splash
    App::Game ---> Game
    App::Instantiator ---> Instantiator
}

@enduml