namespace GameDemo;

using Godot;

/// <summary>
/// Input map generated by the excellent third-party GodotSharp generators.
/// Allows us to access our input constants in a type-safe way.
/// </summary>
[InputMap]
public partial class GameInputs;
