@startuml InGameUILogic
state InGameUILogic {
  state InGameUILogicState
}

[*] --> InGameUILogicState

InGameUILogic : Dependencies:
InGameUILogic : - IAppRepo
InGameUILogic : - IGameRepo
InGameUILogic : - Mock
@enduml