@startuml BaseState
state "BaseState" as GameDemo_InGameAudioLogic_BaseState

GameDemo_InGameAudioLogic_BaseState : OnCoinCollected() → PlayCoinCollected
GameDemo_InGameAudioLogic_BaseState : OnGameEnded() → PlayPlayerDied, StopGameMusic
GameDemo_InGameAudioLogic_BaseState : OnGameEntered() → PlayGameMusic
GameDemo_InGameAudioLogic_BaseState : OnJumped() → PlayJump
GameDemo_InGameAudioLogic_BaseState : OnJumpshroomUsed() → PlayBounce
GameDemo_InGameAudioLogic_BaseState : OnMainMenuEntered() → PlayMainMenuMusic
@enduml