@startuml BaseState
state "BaseState" as GameDemo_BaseState

GameDemo_BaseState : OnCoinCollected() → PlayCoinCollected
GameDemo_BaseState : OnGameEnded() → PlayPlayerDied, StopGameMusic
GameDemo_BaseState : OnGameEntered() → PlayGameMusic
GameDemo_BaseState : OnJumped() → PlayJump
GameDemo_BaseState : OnJumpshroomUsed() → PlayBounce
GameDemo_BaseState : OnMainMenuEntered() → PlayMainMenuMusic
@enduml