@startuml GameLogicState
state "GameLogicState" as GameDemo_GameLogic_GameLogicState {
  state "Lost" as GameDemo_GameLogic_GameLogicState_Lost
  state "MenuBackdrop" as GameDemo_GameLogic_GameLogicState_MenuBackdrop
  state "Paused" as GameDemo_GameLogic_GameLogicState_Paused {
    state "Saving" as GameDemo_GameLogic_GameLogicState_Saving
  }
  state "Playing" as GameDemo_GameLogic_GameLogicState_Playing
  state "Quit" as GameDemo_GameLogic_GameLogicState_Quit
  state "RestartingGame" as GameDemo_GameLogic_GameLogicState_RestartingGame
  state "Resuming" as GameDemo_GameLogic_GameLogicState_Resuming
  state "Won" as GameDemo_GameLogic_GameLogicState_Won
}

GameDemo_GameLogic_GameLogicState_Lost --> GameDemo_GameLogic_GameLogicState_Quit : GoToMainMenu
GameDemo_GameLogic_GameLogicState_Lost --> GameDemo_GameLogic_GameLogicState_RestartingGame : Start
GameDemo_GameLogic_GameLogicState_MenuBackdrop --> GameDemo_GameLogic_GameLogicState_MenuBackdrop : Initialize
GameDemo_GameLogic_GameLogicState_MenuBackdrop --> GameDemo_GameLogic_GameLogicState_Playing : Start
GameDemo_GameLogic_GameLogicState_Paused --> GameDemo_GameLogic_GameLogicState_Quit : GoToMainMenu
GameDemo_GameLogic_GameLogicState_Paused --> GameDemo_GameLogic_GameLogicState_Resuming : PauseButtonPressed
GameDemo_GameLogic_GameLogicState_Paused --> GameDemo_GameLogic_GameLogicState_Saving : SaveRequested
GameDemo_GameLogic_GameLogicState_Playing --> GameDemo_GameLogic_GameLogicState_Lost : EndGame
GameDemo_GameLogic_GameLogicState_Playing --> GameDemo_GameLogic_GameLogicState_Paused : PauseButtonPressed
GameDemo_GameLogic_GameLogicState_Playing --> GameDemo_GameLogic_GameLogicState_Quit : EndGame
GameDemo_GameLogic_GameLogicState_Playing --> GameDemo_GameLogic_GameLogicState_Won : EndGame
GameDemo_GameLogic_GameLogicState_Resuming --> GameDemo_GameLogic_GameLogicState_Playing : PauseMenuTransitioned
GameDemo_GameLogic_GameLogicState_Saving --> GameDemo_GameLogic_GameLogicState_Paused : SaveCompleted
GameDemo_GameLogic_GameLogicState_Saving --> GameDemo_GameLogic_GameLogicState_Saving : PauseButtonPressed
GameDemo_GameLogic_GameLogicState_Won --> GameDemo_GameLogic_GameLogicState_Won : GoToMainMenu

GameDemo_GameLogic_GameLogicState_Lost : OnEnter → ShowLostScreen
GameDemo_GameLogic_GameLogicState_Paused : OnEnter → ShowPauseMenu
GameDemo_GameLogic_GameLogicState_Paused : OnExit → ExitPauseMenu
GameDemo_GameLogic_GameLogicState_Playing : OnEnter → StartGame
GameDemo_GameLogic_GameLogicState_Resuming : OnExit → HidePauseMenu
GameDemo_GameLogic_GameLogicState_Saving : OnEnter → ShowPauseSaveOverlay, StartSaving
GameDemo_GameLogic_GameLogicState_Saving : OnExit → HidePauseSaveOverlay
GameDemo_GameLogic_GameLogicState_Won : OnEnter → ShowWonScreen
@enduml