@startuml PlayerCameraLogic
state "PlayerCameraLogic State" as GameDemo_PlayerCameraLogic_State {
  state "InputDisabled" as GameDemo_PlayerCameraLogic_State_InputDisabled
  state "InputEnabled" as GameDemo_PlayerCameraLogic_State_InputEnabled
}

GameDemo_PlayerCameraLogic_State --> GameDemo_PlayerCameraLogic_State : PhysicsTicked
GameDemo_PlayerCameraLogic_State --> GameDemo_PlayerCameraLogic_State : TargetOffsetChanged
GameDemo_PlayerCameraLogic_State --> GameDemo_PlayerCameraLogic_State : TargetPositionChanged
GameDemo_PlayerCameraLogic_State_InputDisabled --> GameDemo_PlayerCameraLogic_State_InputEnabled : EnableInput
GameDemo_PlayerCameraLogic_State_InputEnabled --> GameDemo_PlayerCameraLogic_State_InputDisabled : DisableInput
GameDemo_PlayerCameraLogic_State_InputEnabled --> GameDemo_PlayerCameraLogic_State_InputEnabled : JoyPadInputOccurred
GameDemo_PlayerCameraLogic_State_InputEnabled --> GameDemo_PlayerCameraLogic_State_InputEnabled : MouseInputOccurred

GameDemo_PlayerCameraLogic_State : OnPhysicsTicked → CameraLocalPositionChanged, CameraOffsetChanged, GimbalRotationChanged, GlobalTransformChanged

[*] --> GameDemo_PlayerCameraLogic_State_InputDisabled
@enduml