@startuml BaseState
state "BaseState" as GameDemo_AppLogic_BaseState {
  state "InGame" as GameDemo_AppLogic_BaseState_InGame
  state "LeavingGame" as GameDemo_AppLogic_BaseState_LeavingGame
  state "LeavingMenu" as GameDemo_AppLogic_BaseState_LeavingMenu
  state "LoadingSaveFile" as GameDemo_AppLogic_BaseState_LoadingSaveFile
  state "MainMenu" as GameDemo_AppLogic_BaseState_MainMenu
  state "SplashScreen" as GameDemo_AppLogic_BaseState_SplashScreen
}

GameDemo_AppLogic_BaseState_InGame --> GameDemo_AppLogic_BaseState_LeavingGame : EndGame
GameDemo_AppLogic_BaseState_LeavingGame --> GameDemo_AppLogic_BaseState_InGame : FadeOutFinished
GameDemo_AppLogic_BaseState_LeavingGame --> GameDemo_AppLogic_BaseState_MainMenu : FadeOutFinished
GameDemo_AppLogic_BaseState_LeavingMenu --> GameDemo_AppLogic_BaseState_InGame : FadeOutFinished
GameDemo_AppLogic_BaseState_LeavingMenu --> GameDemo_AppLogic_BaseState_LoadingSaveFile : FadeOutFinished
GameDemo_AppLogic_BaseState_LoadingSaveFile --> GameDemo_AppLogic_BaseState_InGame : SaveFileLoaded
GameDemo_AppLogic_BaseState_MainMenu --> GameDemo_AppLogic_BaseState_LeavingMenu : LoadGame
GameDemo_AppLogic_BaseState_MainMenu --> GameDemo_AppLogic_BaseState_LeavingMenu : NewGame
GameDemo_AppLogic_BaseState_SplashScreen --> GameDemo_AppLogic_BaseState_MainMenu : FadeOutFinished

GameDemo_AppLogic_BaseState_InGame : OnEnter → ShowGame
GameDemo_AppLogic_BaseState_InGame : OnExit → HideGame
GameDemo_AppLogic_BaseState_LeavingGame : OnFadeOutFinished → RemoveExistingGame, SetupGameScene
GameDemo_AppLogic_BaseState_LeavingMenu : OnEnter → FadeToBlack
GameDemo_AppLogic_BaseState_LoadingSaveFile : OnEnter → StartLoadingSaveFile
GameDemo_AppLogic_BaseState_MainMenu : OnEnter → SetupGameScene, ShowMainMenu
GameDemo_AppLogic_BaseState_SplashScreen : OnEnter → ShowSplashScreen
GameDemo_AppLogic_BaseState_SplashScreen : OnSplashScreenSkipped() → HideSplashScreen
@enduml