@startuml AppLogic
state "AppLogic State" as GameDemo_AppLogic_State {
  state "InGame" as GameDemo_AppLogic_State_InGame
  state "LeavingGame" as GameDemo_AppLogic_State_LeavingGame {
    GameDemo_AppLogic_State_LeavingGame : OnEnter → FadeOut
    GameDemo_AppLogic_State_LeavingGame : OnExit → RemoveExistingGame
  }
  state "LeavingMenu" as GameDemo_AppLogic_State_LeavingMenu {
    GameDemo_AppLogic_State_LeavingMenu : OnEnter → FadeOut
  }
  state "MainMenu" as GameDemo_AppLogic_State_MainMenu {
    GameDemo_AppLogic_State_MainMenu : OnEnter → LoadGame, ShowMainMenu
  }
  state "RestartingGame" as GameDemo_AppLogic_State_RestartingGame {
    GameDemo_AppLogic_State_RestartingGame : OnEnter → FadeOut
    GameDemo_AppLogic_State_RestartingGame : OnExit → LoadGame, RemoveExistingGame
  }
  state "SplashScreen" as GameDemo_AppLogic_State_SplashScreen {
    GameDemo_AppLogic_State_SplashScreen : OnEnter → ShowSplashScreen
    GameDemo_AppLogic_State_SplashScreen : OnSplashScreenSkipped() → HideSplashScreen
  }
}

GameDemo_AppLogic_State_LeavingMenu --> GameDemo_AppLogic_State_InGame : FadeOutFinished
GameDemo_AppLogic_State_MainMenu --> GameDemo_AppLogic_State_LeavingMenu : StartGame
GameDemo_AppLogic_State_RestartingGame --> GameDemo_AppLogic_State_InGame : FadeOutFinished
GameDemo_AppLogic_State_SplashScreen --> GameDemo_AppLogic_State_MainMenu : FadeOutFinished

[*] --> GameDemo_AppLogic_State_SplashScreen
@enduml